version: '3.8'
services:
  database:
    container_name: proj_manag_postgres_java
    image: 'postgres:16.1-alpine3.19'
    ports:
      - 8081:5432
    environment:
      POSTGRES_PASSWORD: 'senha123'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'proj_manag_db'
